version: '3'

services:
  node:
    image: node
    container_name: node
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./assets/node-a:/assets/chain
    environment:
      - GOLINKSD_PORT=8081
      - GOLINKSD_PEER_PORT=8082
      - GOLINKSD_GENESIS=true
      - GOLINKSD_DELAY_STARTUP=0
      - GOLINKSD_AUTH_SERVER=http://localhost:8000